#+title:     OB-APEX
#+author:    tan.nguyen
#+email:     tan.nguyen@furucrm.com

Copyright (C) your name here

Author: tan.nguyen
Keywords: literate programming, reproducible research
Homepage: https://orgmode.org
Version: 0.01

* LICENSE:
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

 + This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 + You should have received a copy of the GNU General Public License
 along with GNU Emacs; see the file COPYING.  If not, write to the
 Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 Boston, MA 02110-1301, USA.
* COMMENTARY:
 This file is not intended to ever be loaded by org-babel, rather it is a
 template for use in adding new language support to Org-babel. Good first
 steps are to copy this file to a file named by the language you are adding,
 and then use `query-replace' to replace all strings of "template" in this
 file with the name of your new language.
 After the `query-replace' step, it is recommended to load the file and
 register it to org-babel either via the customize menu, or by evaluating the
 line: (add-to-list 'org-babel-load-languages '(template . t)) where
 `template' should have been replaced by the name of the language you are
 implementing (note that this applies to all occurrences of 'template' in this
 file).
 After that continue by creating a simple code block that looks like e.g.

 Finally you can use `edebug' to instrumentalize
 `org-babel-expand-body:template' and continue to evaluate the code block. You
 try to add header keywords and change the body of the code block and
 reevaluate the code block to observe how things get handled.

 If you have questions as to any of the portions of the file defined
 below please look to existing language support for guidance.

 If you are planning on adding a language to org-babel we would ask
 that if possible you fill out the FSF copyright assignment form
 available at https://orgmode.org/request-assign-future.txt as this
 will make it possible to include your language support in the core
 of Org-mode, otherwise unassigned language support files can still
 be included in the contrib/ directory of the Org-mode repository.

* REQUIREMENTS:
 Use this section to list the requirements of this language.  Most
 languages will require that at least the language be installed on
 the user's system, and the Emacs major mode relevant to the
 language be installed as well.

* APEX TEMPLATE CODE
** REQUIREMENT LIBS
#+begin_src emacs-lisp :tangle yes
(require 'ob)
(require 'ob-ref)
(require 'ob-comint)
(require 'ob-eval)
(require 'salesforce-api)
#+end_src

** DEFINE EXTENSION
#+begin_src emacs-lisp :tangle yes
(add-to-list 'org-babel-tangle-lang-exts '("cls" . "apex"))
#+end_src

** DEFINE DEFAULT HEADER ARGS
#+begin_src emacs-lisp :tangle yes
;; optionally declare default header arguments for this language
(defvar org-babel-default-header-args:apex '((:tangle . "yes")))
#+end_src

** EXPAND SOURCE CODE
 This function expands the body of a source code block by doing things like
 prepending argument definitions to the body, it should be called by the
 `org-babel-execute:template' function below. Variables get concatenated in
 the `mapconcat' form, therefore to change the formatting you can edit the
 `format' form.
#+begin_src emacs-lisp :tangle yes
(defun org-babel-expand-body:apex (body params &optional processed-params)
  "Expand BODY according to PARAMS, return the expanded body."
  (require 'inf-template nil t)
  (let ((vars
         (org-babel--get-vars
          (or processed-params
              (org-babel-process-params params)))))

    (concat
     (mapconcat #'binding-declare-variable vars "\n")
     "\n" body "\n")))
#+end_src

** EVALUATE APEX CODE
+ This is the main function which is called to evaluate a code
block.

+ This function will evaluate the body of the source code and
return the results as emacs-lisp depending on the value of the
:results header argument
- output means that the output to STDOUT will be captured and
  returned
- value means that the value of the last statement in the
  source code block will be returned

+ The most common first step in this function is the expansion of the
PARAMS argument using `org-babel-process-params'.

+ Please feel free to not implement options which aren't appropriate
for your language (e.g. not all languages support interactive
"session" evaluation).  Also you are free to define any new header
arguments which you feel may be useful -- all header arguments
specified by the user will be available in the PARAMS variable.

#+begin_src emacs-lisp :tangle yes
(defun org-babel-execute:apex (body params)
  (let* ((processed-params (org-babel-process-params params))
         (filter-type (assq :filter-type processed-params))
         (full-body (org-babel-expand-body:apex
                        body params processed-params)))

    (execute-async-apex full-body)))
#+end_src

** EXECUTE APEX BLOCK CODE
#+begin_src emacs-lisp :tangle yes
(defun execute-async-apex (content)
  (let*
   ((uuid (org-id-uuid))
    (current-buffer (buffer-file-name))
    (buffer-name (format "*%s*" uuid))
    (tempfile (make-temp-file "temp-code"))
    (execute-apex-command
      (list "sfdx" "force:apex:execute" "-f" tempfile))
    process)

   (write-region content nil tempfile)

   ;; Clear default result
   (org-babel-remove-result)

   ;; Insert new result with uuid
   (save-excursion
        (re-search-forward "#\\+end_src")
        (insert (format "\n\n#+RESULTS: %s\n %s" "" uuid))

        (sfdx--helper:execute-process
         execute-apex-command
         (lambda (process output buffer)

           (with-current-buffer (find-file current-buffer)
             (goto-char (point-min))
             (re-search-forward uuid)
             (beginning-of-line)
             (kill-line)
             (insert
              (mapconcat
               (lambda (x)
                 (format ": %s" x))
               (split-string output "\n")
               "\n"))))))))

(defun binding-declare-variable (pair)
  (let* ((var
          (split-string
            (format "%s"(car pair)) "\\."))
         (var-type (car var))
         (var-name (car (cdr var)))
         (value
          (org-babel-template-var-to-template
           (cdr pair))))

    (format
     "%s %s = %s;"
     var-type
     var-name
     (if (string= var-type "String")
       (format "'%s'" value)
       value))))

(defun org-babel-prep-session:apex (session params)
  "Prepare SESSION according to the header arguments specified in PARAMS.")


(defun org-babel-template-var-to-template (var)
  "Convert an elisp var into a string of template source code
specifying a var of the same value."
  (format "%s" var))

(defun org-babel-template-table-or-string (results)
  "If the results look like a table, then convert them into an
Emacs-lisp table, otherwise return the results as a string.")


(defun org-babel-template-initiate-session (&optional session)
  "If there is not a current inferior-process-buffer in SESSION then create.
Return the initialized session."
  (unless (string= session "none")))

(provide 'ob-apex)
#+end_src
