#+title:     SALESFORCE-MINOR-MODE
#+author:    tan.nguyen
#+email:     tan.nguyen@furucrm.com


* TABLE OF CONTENTS :toc_4:
- [[#minor-mode][MINOR MODE]]
  - [[#requirement][REQUIREMENT]]
  - [[#config-variable][CONFIG VARIABLE]]
  - [[#salesforce-functions][SALESFORCE FUNCTIONS]]
    - [[#functions-use-force-prefix][FUNCTIONS USE FORCE PREFIX]]
      - [[#push-source-salesforce-to-org][PUSH SOURCE SALESFORCE TO ORG]]
      - [[#retrieve-source-salesforce-from-org][RETRIEVE SOURCE SALESFORCE FROM ORG]]
    - [[#functions-use-org-prefix][FUNCTIONS USE ORG PREFIX]]
      - [[#open-org-within-ctable][OPEN ORG WITHIN CTABLE]]
      - [[#open-org-project][OPEN ORG PROJECT]]
      - [[#display-all-org][DISPLAY ALL ORG]]
      - [[#show-org-connect-status][SHOW ORG CONNECT STATUS]]
      - [[#get-default-org][GET DEFAULT ORG]]
      - [[#refresh-org][REFRESH ORG]]
    - [[#functions-use-apex-prefix][FUNCTIONS USE APEX PREFIX]]
      - [[#idea-apex-logs][IDEA APEX LOGS]]
      - [[#proj-apex-log][PROJ APEX LOG]]
      - [[#execute-apex-code][EXECUTE APEX CODE]]
    - [[#functions-use-login-prefix][FUNCTIONS USE LOGIN PREFIX]]
      - [[#scratchsanbox-org][SCRATCH/SANBOX ORG]]
      - [[#productiondev-org][PRODUCTION/DEV ORG]]
    - [[#functions-salesforce-query-records][FUNCTIONS SALESFORCE QUERY RECORDS]]
      - [[#soql-string][SOQL STRING]]
      - [[#soql-file][SOQL FILE]]
    - [[#compare-local-file-with-org-file][COMPARE LOCAL FILE WITH ORG FILE]]
    - [[#functioncs-generate-metadata][FUNCTIONCS GENERATE METADATA]]
      - [[#visualforce-page][VISUALFORCE PAGE]]
      - [[#visualforce-component][VISUALFORCE COMPONENT]]
      - [[#apex-class][APEX CLASS]]
      - [[#lightning-metadata][LIGHTNING METADATA]]
    - [[#function-apex-test-01][FUNCTION APEX TEST]]
      - [[#run-all-tests-class][RUN ALL TESTS CLASS]]
      - [[#run-local-test-classes][RUN LOCAL TEST CLASSES]]
      - [[#--run-specific-unit-test][[ ] RUN SPECIFIC UNIT TEST]]
    - [[#run-lwc-local-server][RUN LWC LOCAL SERVER]]
  - [[#internal-functions][INTERNAL FUNCTIONS]]
    - [[#get-errors][GET ERRORS]]
    - [[#generate-command][GENERATE COMMAND]]
    - [[#execute-apex-code-1][EXECUTE APEX CODE]]
    - [[#excute-soql-block][EXCUTE SOQL BLOCK]]
    - [[#make-synchronous-process][MAKE SYNCHRONOUS PROCESS]]
    - [[#make-asynchronous-process][MAKE ASYNCHRONOUS PROCESS]]
    - [[#execute-synchronous-salesforce-command][EXECUTE SYNCHRONOUS SALESFORCE COMMAND]]
    - [[#execute-asynchronous-salesforce-command][EXECUTE ASYNCHRONOUS SALESFORCE COMMAND]]
    - [[#convert-hashtable-to-list-data][CONVERT HASHTABLE TO LIST DATA]]
    - [[#custom-map-list-function][CUSTOM MAP LIST FUNCTION]]
    - [[#extract-data-in-hashtable][EXTRACT DATA IN HASHTABLE]]
  - [[#build-table-functions][BUILD TABLE FUNCTIONS]]
    - [[#build-ctable-component][BUILD CTABLE COMPONENT]]
    - [[#build-ctable-header-table][BUILD CTABLE HEADER TABLE]]
  - [[#helpers-functions][HELPERS FUNCTIONS]]
    - [[#key-binding-functions][KEY BINDING FUNCTIONS]]
    - [[#hook-functions][HOOK FUNCTIONS]]
  - [[#define-minor-mode][DEFINE MINOR MODE]]
- [[#org-babel-apex][ORG BABEL APEX]]
  - [[#dependencies][DEPENDENCIES]]
  - [[#extensions][Extensions]]
  - [[#default-header-args][DEFAULT HEADER ARGS]]
  - [[#expand-source-code][EXPAND SOURCE CODE]]
  - [[#evaluate-apex-code][EVALUATE APEX CODE]]
  - [[#execute-apex-block-code][EXECUTE APEX BLOCK CODE]]
- [[#log-mode][LOG MODE]]
- [[#org-babel-apex-log][ORG BABEL APEX LOG]]
  - [[#dependencies-1][DEPENDENCIES]]
  - [[#define-headers][DEFINE HEADERS]]
  - [[#expand-body-apex-log][EXPAND BODY APEX LOG]]
  - [[#execute-apex-log][EXECUTE APEX LOG]]
  - [[#run-test-class][RUN TEST CLASS]]
  - [[#filter-log-content][FILTER LOG CONTENT]]

* MINOR MODE
** REQUIREMENT
#+begin_src emacs-lisp :tangle yes
(require 'alert)
(require 'projectile)
(require 'ctable)
(require 'subr-x)
(require 'cl-lib)
#+end_src

** CONFIG VARIABLE
#+begin_src emacs-lisp :tangle yes
(defcustom sfmm:keymap-prefix "M-o"
  "The prefix for salesforce-mode key bindings."
  :type 'string
  :group 'salesforce)

(defcustom sfmm:org-keymap-prefix "O"
  "The keymap prefix for Org function"
  :type 'string
  :group 'salesforce)

(defcustom sfmm:auth-keymap-prefix "A"
  "The keymap prefix for Auth function"
  :type 'string
  :group 'salesforce)

(defcustom sfmm:apex-keymap-prefix "C"
  "The keymap prefix for Apex function"
  :type 'string
  :group 'salesforce)

(defcustom sfmm:query-keymap-prefix "Q"
  "The keymap prefix for Database function"
  :type 'string
  :group 'salesforce)

(defcustom sfmm:tangle-on-save t
  "When t, automatically tangle Org files on save."
  :type 'boolean
  :group 'salesforce)

(defcustom sfmm:api-version nil
  "Custom define api version for command"
   :type 'string
   :group 'salesforce-cli)

(defcustom sfmm:package-dir "manifest"
  "Custom define api version for command"
   :type 'string
   :group 'salesforce-cli)

(defcustom sfmm:non-scratch-org-header-display
  '("username" "instanceUrl" "orgId" "isDevHub" "instanceApiVersion" "alias" "lastUsed" "connectedStatus")
  "Custom define header display on table non scratch orgs"
  :type 'list
  :group 'salesforce-cli)

(defcustom sfmm:scratch-org-header-display
  '("username" "password" "instanceUrl" "orgId" "expirationDate" "instanceApiVersion" "alias" "connectedStatus")
  "Custom define header display on table scratch orgs"
  :type 'list
  :group 'salesforce-cli)

(defcustom sfmm:sfdx-lib-alias "sf"
  ""
  :type 'string
  :group 'command-alias)

(defcustom sfmm:sfdx-legacy-alias "force"
 ""
 :type 'string
 :group 'command-alias)

(defcustom sfmm:project-command-alias "project"
  ""
  :type 'string
  :group 'command-alias)

(defcustom sfmm:data-command-alias "data"
  ""
  :type 'string
  :group 'command-alias)

(defcustom sfmm:visualforce-command-alias "visualforce"
  ""
  :type 'string
  :group 'command-alias)

(defcustom sfmm:apex-command-alias "apex"
  ""
  :type 'string
  :group 'command-alias)

(defcustom sfmm:org-command-alias "org"
  ""
  :type 'string
  :group 'command-alias)

(defcustom sfmm:lightning-command-alias "lightning"
  ""
  :type 'string
  :group 'command-alias)

(defcustom sfmm:project-deploy-command
  (concat sfmm:project-command-alias " " "deploy")
  ""
  :type 'string
  :group 'project-command)

(defcustom sfmm:project-retrieve-command
  (concat sfmm:project-command-alias " " "retrieve")
  ""
  :type 'string
  :group 'project-command)

(defcustom sfmm:default-browser "qutebrowser"
  "Browser use for open url"
  :type 'string
  :group 'sfdx-cli)

(defcustom sfmm:default-apex-class-path "force-app/main/default/classes"
 "Path save apex classes"
 :type 'string
 :group 'sfdx-config)

(defcustom sfmm:default-lwc-path "force-app/main/default/lwc"
 "Path save lwc components"
 :type 'string
 :group 'sfdx-config)

(defcustom sfmm:default-aura-path "force-app/main/default/aura"
 "Path save aura components"
 :type 'string
 :group 'sfdx-config)

(defcustom sfmm:default-test-path "force-app/main/default/lightningTests"
 "Path save test components"
 :type 'string
 :group 'sfdx-config)
#+end_src

** SALESFORCE FUNCTIONS
#+begin_src emacs-lisp :tangle yes
(add-to-list
 'display-buffer-alist
  '("salesforce api.*" . (display-buffer-no-window . nil)))

#+end_src

*** FUNCTIONS USE FORCE PREFIX
**** PUSH SOURCE SALESFORCE TO ORG
#+begin_src emacs-lisp :tangle yes
(defun sfmm:push-file
    ()
  "Push source salesforce to org"
  (interactive)
  (let* ((push-command (list sfmm:sfdx-lib-alias "force" "source" "deploy" "-p" buffer-file-name "--json")))

    (sfmm--helper:make-async-process
     :command push-command
     :handle-success-lambda
     `(lambda (process json-instance buffer)
       (alert (format "Deploy %s success" ,buffer-file-name)
              :title "Salesforce Alert"))

     :handle-error-lambda
     `(lambda (process json-instance buffer)
       (alert (format "Deploy %s failures:\n %s"
                     ,buffer-file-name
                     (sfmm--helper:get-errors-json json-instance)
               :title "Salesforce Alert"))))))
#+end_src
**** RETRIEVE SOURCE SALESFORCE FROM ORG
#+begin_src emacs-lisp :tangle yes
(defun sfmm:retrieve-file
    ()
  "Retrieve source salesforce form org"
  (interactive)
  (let ((retrieve-command (list sfmm:sfdx-lib-alias "force" "source" "retrieve" "-p" buffer-file-name "--json")))

    (sfmm--helper:make-async-process
     :command retrieve-command
     :handle-success-lambda
     `(lambda (process json-instance buffer)
        (alert (format "Retrieve %s success" ,buffer-file-name)
               :title "Salesforce Alert")))))
#+end_src
*** FUNCTIONS USE ORG PREFIX
**** OPEN ORG WITHIN CTABLE
#+begin_src emacs-lisp :tangle yes
(defun sfmm:org:specific-open ()
   "Use a specific user name to open org"
   (interactive)
   (let ((user-name (ctbl:cp-get-selected-data-cell (ctbl:cp-get-component))))

     (unless user-name
       (setq user-name (read-string "user-name: ")))

     (sfmm--helper:make-sync-process
      :command
      (sfmm--helper:generate-command (list "org" "open" "--json" "-o" user-name "-r"))
      :handle-success-lambda
      (lambda (process json-instance buffer)
        (let ((url (sfmm--helper:get-data-hashtable "result.url" json-instance)))

          (shell-command (format "%s --target %s %S"
                                 sfmm:default-browser
                                 "tab"
                                 url)))))))
#+end_src

**** OPEN ORG PROJECT
#+begin_src emacs-lisp :tangle yes
(defun sfmm:org:default-open ()
   "Open default org"
   (interactive)
   (let ((command (sfmm--helper:generate-command (list "org" "open" "--json" "-r"))))

     (sfmm--helper:make-async-process
      :command command
      :handle-success-lambda
      (lambda (process json-instance buffer)
        (let ((url (sfmm--helper:get-data-hashtable "result.url" json-instance)))

          (shell-command (concat sfmm:default-browser " " (format "%S" url) " " "&")))))))
#+end_src

**** DISPLAY ALL ORG
#+begin_src emacs-lisp :tangle yes
(defun sfmm:display-all-org (org-type)
  "Display all current connect org"
  (let ((command (sfmm--helper:generate-command (list sfmm:org-command-alias "list" "--json"))))

    (sfmm--helper:make-sync-process
     :command command
     :handle-success-lambda
     (lambda (process json-instance buffer)
       (let ((start-index 1)
             (column-header-map #s(hash-table test equal data ("No" ((:align . 'left) (:title . "No"))))))
         (mapcar
          (lambda (item)
            (puthash
             (format "%s" item)
             `((:align . ,'left) (:title . ,item))
             column-header-map))
          (cond ((string= org-type "nonScratchOrgs") sfmm:non-scratch-org-header-display)
                ((string= org-type "scratchOrgs")) sfmm:scratch-org-header-display))

         (if (= (gethash "status" json-instance) 0)
             (let* ((non-scratch-orgs
                     (sfmm--helper:get-data-hashtable
                      (concat "result." org-type) json-instance))
                    (data
                     (mapcar
                      (lambda (element)
                        (let ((row
                               (sfmm--helper:convert-hashtable-data-to-list
                                :hashtable-data element
                                :columns
                                (cond ((string= org-type "nonScratchOrgs") sfmm:non-scratch-org-header-display)
                                      ((string= org-type "scratchOrgs")) sfmm:scratch-org-header-display)
                                :post-process
                                (lambda (key value)
                                  (let ((column-config
                                         `((:align . ,'left) (:title . ,key))))

                                    (when (length> value 50)
                                        (add-to-list 'column-config `(:max-width . ,'50))

                                        (puthash (format "%s" key) column-config column-header-map)))))))

                          (progn
                            (add-to-list 'row start-index
                                         nil (lambda (el1 el2) nil))
                            (setq start-index
                                  (1+ start-index))
                            row)))
                      non-scratch-orgs)))

               (sfdx--build:make-table-component
                :column-header (hash-table-values column-header-map)
                :data data
                :buffer buffer))))))))
#+end_src
***** NON SCRATCH ORG
#+begin_src emacs-lisp :tangle yes
(defun sfmm:display-all-non-scratch-orgs ()
  (interactive)
  (sfmm:display-all-org "nonScratchOrgs"))
#+end_src
***** SCRATCH ORG
#+begin_src emacs-lisp :tangle yes
(defun sfmm:display-all-scratch-orgs ()
  (interactive)
  (sfmm:display-all-org "scratchOrgs"))
#+end_src
**** SHOW ORG CONNECT STATUS
#+begin_src emacs-lisp :tangle yes
(defun sf:org:connect-status ()
  "Check connect status to org"
  (let ((display-org-information-command (sfmm--helper:generate-command (list sfmm:org-command-alias "display" "--json"))))

    (sfmm--helper:make-async-process
     :command display-org-information-command
     :handle-success-lambda
     (lambda (process json-instance buffer)
        (let* ((status (sfmm--helper:get-data-hashtable "result.connectedStatus" json-instance)))
          (when (string= status
                         "RefreshTokenAuthError")
            (alert "Token expired !!" :title "Salesforce Alert")))))))
#+end_src
**** TODO GET DEFAULT ORG
#+begin_src emacs-lisp :tangle yes
(defun sfmm:org:show-current-org ()
  (let ((org-alias ""))

    (sfmm--helper:make-async-process
     :command (sfmm--helper:generate-command (list sfmm:org-command-alias "display" "--json"))
     :handle-success-lambda
     `(lambda (process json-instance buffer)
        (setq ,'org-alias (sfmm--helper:get-data-hashtable "result.alias" json-instance))))
    org-alias))
#+end_src
**** REFRESH ORG
#+begin_src emacs-lisp :tangle yes
(defun sfmm:refresh-default-org
    ()
  "Refresh current default org on layout"
  (interactive)
  (sfmm:org:show-current-org))
#+end_src
*** FUNCTIONS USE APEX PREFIX
**** IDEA APEX LOGS
#+begin_src emacs-lisp :tangle no
(defun sfmm:apex:get-all-log ()
  "Get log apex"
  (interactive)
  (let ((command (sfmm--helper:generate-command (list sfmm:apex-command-alias "list" "log" "--json"))))

    (sfmm--helper:make-sync-process
     :command command
     :handle-success-lambda
     (lambda (process json-instance buffer)
       (let* ((records-list (sfmm--helper:get-data-hashtable "result" json-instance))
              (start-index 1)
              (column-header-map #s(hash-table test equal data ("No" ((:align . 'left) (:title . "No")))))
              (data
               (mapcar
                (lambda (element)

                  (let ((row `(,start-index)))
                    (maphash
                     (lambda (key value)
                       (let ((column-config `((:align . ,'left) (:title . ,key))))
                         (unless (hash-table-p value)
                           (when (eq value ':null)
                             (setq value " "))
                           (when (eq value ':false)
                             (setq value "False"))
                           (when (eq value 't)
                             (setq value "True"))

                           (add-to-list 'row
                                        (replace-regexp-in-string "\\([\n]\\)" "" value) 1
                                        '(lambda (element1 element2) nil))

                           (when (length> value 50)
                             (add-to-list 'column-config `(:max-width . ,'50)))

                           (puthash (format "%s" key) column-config column-header-map))))
                     element)
                    (setq start-index (1+ start-index))
                    row))
                records-list))))))))
#+end_src
**** PROJ APEX LOG
***** GET LOG
#+begin_src emacs-lisp :tangle yes
(cl-defun sfmm:apex:get-log (&key log-id number org post-log-handle)
  "Get log apex"
  (let ((command (sfmm--helper:generate-command (list sfmm:apex-command-alias "get" "log" "--json"))))

    (setq command (progn
                    (when org
                     (append command `("-o" ,org)))
                    (cond ((not (string= log-id "")) (append command `("--log-id" ,log-id)))
                          (number (append command `("--number" ,number))))))

    (sfmm--helper:make-async-process
     :command command
     :handle-success-lambda
     `(lambda (process json-instance buffer)

        (setq json-result (gethash "result" json-instance))
        (funcall ,post-log-handle (gethash "log" (aref json-result 0)))))))
#+end_src
***** PROJ GET FILTER LOG
#+begin_src emacs-lisp :tangle no
(cl-defun sfmm:log:get-filter-log ()
  "Get log with filter condition"
  (interactive)
  (let ((filter-type (read-string "Filter: "))
        (log-id-or-number-log (read-string "Log id or number log: "))
        (org (read-string "read-string")))))

#+end_src
**** TODO EXECUTE APEX CODE
#+begin_src emacs-lisp :tangle yes
(defun sfmm:execute-apex-code ()
 (interactive)
 (sfmm--helper:execute-apex (point-min)))
#+end_src
*** FUNCTIONS USE LOGIN PREFIX
#+begin_src emacs-lisp :tangle yes
(defun sfmm--helper:org:login (url)
   "Authorize to salesforce org"
   (let* ((alias (read-string "alias: "))
          (authorize-command
            (sfmm--helper:generate-command (list sfmm:org-command-alias "login" "web" "-a" alias "--instanceurl" url "--set-default" "--json"))))
    (sfmm--helper:make-async-process
     :command
     authorize-command
     :handle-success-lambda
     (lambda (process json-instance buffer)
       (let ((user-name (sfmm--helper:get-data-hashtable "result.username" json-instance)))

         (alert "Authorize success" :title "Salesforce Alert")
         (sfmm--helper:make-sync-process
          :command
          (sfmm--helper:generate-command (list "org" "open" "--json" "-o" user-name))
          :handle-success-lambda
          (lambda (process json-instance buffer)
            (let ((url (sfmm--helper:get-data-hashtable "result.url" json-instance)))

              (shell-command (concat sfmm:default-browser " " (format "%S" url) " " "&"))))))))))
#+end_src
**** SCRATCH/SANBOX ORG
#+begin_src emacs-lisp :tangle yes
(defun sfmm:org:authorize-sandbox ()
  "Authorize use for scratch org and sanbox org"
  (interactive)
  (let* ((url "https://test.salesforce.com"))

    (sfmm--helper:org:login url)))
#+end_src
**** PRODUCTION/DEV ORG
#+begin_src emacs-lisp :tangle yes
(defun sfmm:org:authorize-production ()
  "Authorize use for dev org and production org"
  (interactive)
  (let* ((url "https://login.salesforce.com"))

    (sfmm--helper:org:login url)))
#+end_src

*** FUNCTIONS SALESFORCE QUERY RECORDS
**** SOQL STRING
#+begin_src emacs-lisp :tangle yes
(defun sfmm:fetch-record-through-soql ()
  "Fetch salesforce record by calling API through Salesforce CLI library"
  (interactive)
  (let ((soql-string (read-string "SOQL: ")))

    (sfmm--helper:execute-soql :query soql-string)))
#+end_src
**** SOQL FILE
#+begin_src emacs-lisp :tangle yes

#+end_src
*** COMPARE LOCAL FILE WITH ORG FILE
#+begin_src emacs-lisp :tangle yes
(defun sfmm:fetch-salesforce-file
    ()
  "Retrieve org file from salesforce"
  (let* ((local-path (expand-file-name "~/.cache/sfdx"))
         ())

    ))
#+end_src
*** FUNCTIONCS GENERATE METADATA
**** VISUALFORCE PAGE
#+begin_src emacs-lisp :tangle yes
(defun sfmm:visualforce:generate-page ()
  (interactive)
  (let* ((page-name (read-string "page name: "))
         (page-label (read-string "page label: "))
         (command (sfmm--helper:generate-command
                   (list sfmm:visualforce-command-alias "generate" "page" "--name" page-name "--label" page-label))))

    (sfmm--helper:make-sync-process
     :command command
     :handle-success-lambda
     `(lambda (process json-instance buffer)

        (alert (format "Create visualforce page" ,page-name)
               :title "Salesforce Alert")))))
#+end_src
**** VISUALFORCE COMPONENT
#+begin_src emacs-lisp :tangle yes
(defun sfmm:visualforce:generate-component ()
  (interactive)
  (let* ((page-name (read-string "page name: "))
         (page-label (read-string "page label: "))
         (command (sfmm--helper:generate-command
                   (list sfmm:visualforce-command-alias "generate" "component" "--name" page-name "--label" page-label))))

    (sfmm--helper:make-sync-process
     :command command
     :handle-success-lambda
     `(lambda (process json-instance buffer)

        (alert (format "Create visualforce page" ,page-name)
               :title "Salesforce Alert")))))
#+end_src
**** APEX CLASS
#+begin_src emacs-lisp :tangle yes
(defun sfmm:apex:generate-class ()
  "Generate apex class"
  (interactive)
  (let* ((class-name (read-string "class name: "))
         (class-extend (read-string "class parent: "))
         (class-implements (read-string "class implements: "))
         (command (sfmm--helper:generate-command
                   (list sfmm:apex-command-alias "generate" "class" "--name" class-name "--output-dir" (projectile-expand-root sfmm:default-apex-class-path) "--json")))
         (class-expand ""))

    (progn
      (unless (string= class-extend "")
        (setq class-expand (concat class-expand "extends" " " class-extend " ")))
      (unless (string= class-implements "")
        (setq class-expand (concat class-expand "implements" " " class-implements " "))))

    (sfmm--helper:make-async-process
     :command command
     :handle-success-lambda
     `(lambda (process json-instance buffer)
        (let ((full-path-file ,(concat (projectile-expand-root sfmm:default-apex-class-path) "/" class-name ".cls")))
          (org-open-file full-path-file)

          (goto-char (- (point-at-eol) 1))
          (insert ,class-expand))))))
#+end_src
***** TEST CLASS
#+begin_src emacs-lisp :tangle yes
(defun sfmm:apex:generate-test-class ()
  "Generate apex test class"
  (interactive)
  (let* ((class-name (read-string "class name: "))
         (command (sfmm--helper:generate-command
                   (list sfmm:apex-command-alias "generate" "class" "--name" class-name "--output-dir" (projectile-expand-root sfmm:default-apex-class-path) "--json"))))

    (sfmm--helper:make-async-process
     :command command
     :handle-success-lambda
     `(lambda (process json-instance buffer)
        (let ((full-path-file ,(concat (projectile-expand-root sfmm:default-apex-class-path) "/" class-name ".cls")))
          (org-open-file full-path-file)

          (insert "@isTest"))))))
#+end_src
***** METHOD TEST
#+begin_src emacs-lisp :tangle yes
(defun sfmm:apex:generate-test-method ()
  "Generate apex test method"
  (interactive)
  (let ((method-name (read-string "method name: ")))

    (end-of-buffer)
    (forward-line -1)
    (insert (format "\n%s\nprivate static void %s () {\n}"
                    "@isTest"
                    method-name))))
#+end_src
**** LIGHTNING METADATA
#+begin_src emacs-lisp :tangle yes
(cl-defun sfmm:lightning:generate
    (&key type output-dir message-success (component-type ""))
  ""
  (let* ((component-name (read-string "lwc name: "))
         (command (sfmm--helper:generate-command
                    (list sfmm:lightning-command-alias "generate" "component" "--output-dir" output-dir "--name" component-name "--json"))))

    (when (string= type "component")
      (append command (list "--type" component-type)))

    (sfmm--helper:make-sync-process
     :command command
     :handle-success-lambda
     `(lambda (process json-instance buffer)
        (alert (format message-success ,component-name)
               :title "Salesforce Alert")))))
#+end_src
***** LWC
#+begin_src emacs-lisp :tangle yes
(defun sfmm:lightning-component:generate-lwc ()
  ""
  (interactive)
  (sfmm:lightning:generate
   :type "component"
   :output-dir (projectile-expand-root sfmm:default-lwc-path)
   :message-success "Create %s success"
   :component-type "lwc"))
#+end_src
***** AURA
#+begin_src emacs-lisp :tangle yes
(defun sfmm:lightning-component:generate-aura ()
  "Generate Aura Component"
  (interactive)
  (sfmm:lightning:generate
   :type "component"
   :output-dir (projectile-expand-root sfmm:default-aura-path)
   :message-success "Create aura component %s success"
   :component-type "aura"))
#+end_src
***** LIGHTNING APP
#+begin_src emacs-lisp :tangle yes
(defun sfmm:lightning-app:generate ()
  "Create lightning app"
  (interactive)
  (sfmm:lightning:generate
   :type "app"
   :output-dir (projectile-expand-root sfmm:default-aura-path)
   :message-success "Create app %s sucesss"))
#+end_src
***** EVENT
#+begin_src emacs-lisp :tangle yes
(defun sfmm:lightning-event:generate ()
  "Create lightning event"
  (interactive)
  (sfmm:lightning:generate
   :type "event"
   :output-dir (projectile-expand-root sfmm:default-aura-path)))
#+end_src
***** INTERFACE
#+begin_src emacs-lisp :tangle yes
(defun sfmm:lightning-interface:generate ()
  "Create lightning interface"
  (interactive)
  (sfmm:lightning:generate
   :type "interface"
   :output-dir (projectile-expand-root sfmm:default-aura-path)
   :message-success "Create interface %s success"))
#+end_src
***** TEST
#+begin_src emacs-lisp :tangle yes
(defun sfmm:lightning-test:generate ()
  "Create lightning test"
  (interactive)
  (sfmm:lightning:generate
   :type "test"
   :output-dir (projectile-expand-root sfmm:default-test-path)
   :message-success "Create test %s sucess"))
#+end_src
*** TODO FUNCTION APEX TEST [0/1]
#+begin_src emacs-lisp :tangle yes
(cl-defun sfmm:apex:get-result-test-job
    (&key job-id)
  "Get result tests"
  (let ((command (sfmm--helper:generate-command (list sfmm:apex-command-alias "get" "test" "-i" job-id "--json"))))

    (sfmm--helper:make-async-process
     :command command
     :handle-success-lambda
     (lambda (process json-instance buffer)
       (let ((result-tests
              (mapconcat (lambda (result-test)
                           (let ((stack-trace (gethash "StackTrace" result-test))
                                 (outcome (gethash "Outcome" result-test))
                                 (error-message (gethash "Message" result-test))
                                 (method-name (gethash "MethodName" result-test))
                                 (class-name-test (sfmm--helper:get-data-hashtable "ApexClass.Name" result-test)))

                             (format "Class: %s\nMethod: %s\nResult: %s\n%s"
                                     class-name-test
                                     method-name
                                     (cond ((equal error-message ':null)
                                            outcome)
                                           (error-message
                                            error-message))
                                     (cond ((equal stack-trace ':null)
                                            "")
                                           (stack-trace
                                            stack-trace)))))

                         (sfmm--helper:get-data-hashtable "result.tests" json-instance)
                         "\n")))
         (alert result-tests
                :title "Salesforce Alert"))))))
#+end_src
**** RUN ALL TESTS CLASS
#+begin_src emacs-lisp :tangle yes
(defun sfmm:apex:run-test-class ()
  "Run unit test for class"
  (interactive)
  (let ((command (sfmm--helper:generate-command (list sfmm:apex-command-alias "run" "test" "--tests" (file-name-base) "--test-level" "RunSpecifiedTests" "--json"))))

    (sfmm--helper:make-async-process
     :command command
     :handle-success-lambda
     (lambda (process json-instance buffer)
       (alert "Class tests run success"
              :title "Salesforce Alert")
       (sfmm:apex:get-result-test-job
        :job-id (sfmm--helper:get-data-hashtable "result.testRunId" json-instance))))))
#+end_src
**** RUN LOCAL TEST CLASSES
#+begin_src emacs-lisp
(defun sfmm:apex:run-local-tests ()
  "Run all tests class expect tests class in org managed package"
  (interactive)
  (let ((command (sfmm--helper:generate-command (list sfmm:apex-command-alias "run" "test" "--test-level" "RunLocalTests" "--json"))))

    (sfmm--helper:make-async-process
     :command command
     :handle-success-lambda
     (lambda (process json-instance buffer)
       (sfmm:apex:get-result-test-job (job-id (sfmm--helper:get-data-hashtable "result.testRunId" json-instance)))))))
#+end_src
**** [ ] RUN SPECIFIC UNIT TEST
#+begin_src emacs-lisp

#+end_src
*** RUN LWC LOCAL SERVER
#+begin_src emacs-lisp :tangle yes
(defun sfmm:server:local-lwc ()
  ""
  (interactive)
  (let ((command (sfmm--helper:generate-command (list sfmm:sfdx-legacy-alias "lightning" "lwc" "start" "--json"))))

    (sfmm--helper:make-async-process
     :command command
     :handle-success-lambda
     `(lambda (process json-string buffer)
        (alert "Start lwc local server success"
               :title "Salesforce Alert")))))
#+end_src
** INTERNAL FUNCTIONS
*** GET ERRORS
#+begin_src emacs-lisp :tangle yes
(defun sfmm--helper:get-errors-json (data)
   "Get errors from json data"
   (let ((component-failures (sfmm--helper:get-data-hashtable "result.deployedSource" data)))

     (mapconcat
      (lambda (component)
        (let ((problem (gethash "error" component))
              (problem-type (gethash "problemType" component))
              (line-number (gethash "lineNumber" component))
              (file-name (gethash "filePath" component)))

          (format "problem-type: %s \n problem: %s \n %s:%s"
                  problem-type
                  problem
                  file-name
                  line-number)))

      component-failures
      "\n")))
#+end_src

*** GENERATE COMMAND
#+begin_src emacs-lisp :tangle yes
(defun sfmm--helper:generate-command (commands)
  (add-to-list 'commands sfmm:sfdx-lib-alias))
#+end_src
*** EXECUTE APEX CODE
#+begin_src emacs-lisp :tangle yes
(defun sfmm--helper:execute-apex (content)
emacs make-process pipe  "Execute code"
  (let ((code (unless content
               (point-min)
               content))
        (temp-file (make-temp-file "temp_code")))

   (write-region (point-min) (point-max) temp-file)
   (setq execute-apex-code-command
     (sfmm--helper:generate-command "apex" "run" "-f" temp-file))

   (async-shell-command execute-apex-code-command buffer)))
#+end_src
*** EXCUTE SOQL BLOCK
This function execute [[https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_data.htm#cli_reference_force_data_soql_query][command]] from library [[https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_intro.htm][Salesforce CLI]]
- Reference: sfdx-fetch-record-through-soql
- Params:
+ params-command: A list of params is used by Salesforce SOQL command, supporting the following type:
    + user: the user is used to executing command
    + api-version: version API is using
    + query: SOQL string want to execute
    + file: file contains chain SOQL want to execute
    + format: format for result return from API

#+begin_src emacs-lisp :tangle yes
(cl-defun sfmm--helper:execute-soql (&key query (type 'string) (options '("--json")))
  "Excute command fetch records from Salesforce through API"
  (let* ((options
          (cond ((equal type 'string)
                 (list "--query" query))
                ((equal type 'file)
                 (list "--file" query))))
         (execute-soql-code
          (append (sfmm--helper:generate-command (list sfmm:data-command-alias "query"))
                  options)))

    (sfmm--helper:make-async-process
     :command execute-soql-code
     :handle-success-lambda
     (lambda (process json-instance buffer)
       (let* ((records-list (sfmm--helper:get-data-hashtable "result.records" json-instance))
              (start-index 1)
              (column-header-map #s(hash-table test equal data ("No" ((:align . 'left) (:title . "No")))))
              (data
               (mapcar
                (lambda (element)

                  (let ((row `(,start-index)))
                    (maphash
                     (lambda (key value)
                       (let ((column-config `((:align . ,'left) (:title . ,key))))
                         (unless (hash-table-p value)
                           (when (eq value ':null)
                             (setq value " "))
                           (when (eq value ':false)
                             (setq value "False"))
                           (when (eq value 't)
                             (setq value "True"))

                           (add-to-list 'row
                                        (replace-regexp-in-string "\\([\n]\\)" "" value) 1
                                        '(lambda (element1 element2) nil))

                           (when (length> value 50)
                             (add-to-list 'column-config `(:max-width . ,'50)))

                           (puthash (format "%s" key) column-config column-header-map))))
                     element)
                    (setq start-index (1+ start-index))
                    row))
                records-list)))
         (sfdx--build:make-table-component
          :column-header (hash-table-values column-header-map)
          :data data
          :buffer buffer))))))
#+end_src

*** MAKE SYNCHRONOUS PROCESS
+ set readonly for overview buffer, edit the buffer through key-bind
#+begin_src emacs-lisp :tangle yes
(cl-defun sfmm--helper:make-sync-process (&key command handle-success-lambda (handle-error-lambda))
  (with-environment-variables (("NODE_NO_WARNINGS" "1"))

    (let* ((buffer-stdout (generate-new-buffer "salesforce-process"))
           (process-identity "salesforce-process")
           (buffer-view-post-process (generate-new-buffer "Salesforce Overview"))
           (process-output "")
           (process
            (make-process
             :name process-identity
             :buffer buffer-stdout
             :command command
             :connection-type 'pipe
             :filter
             (lambda (process output)
               (setq process-output (concat process-output output)))
             :sentinel
             (lambda (process event)
              (cond ((string= event "deleted\n")
                     (kill-buffer (process-buffer process))))))))

      (when (accept-process-output process))

      (if (json-available-p)
          (let ((json-instance (json-parse-string process-output)))
            (if (= (gethash "status" json-instance) 0)
                (funcall handle-success-lambda process json-instance buffer-view-post-process)
              (if handle-error-lambda
                  (funcall handle-error-lambda process json-instance buffer-view-post-process)

                (alert (format "context: %s \nmessage: %s "
                               (gethash "context" json-instance)
                               (gethash "message" json-instance)
                               :title "Salesforce Alert")))))))))
#+end_src

*** MAKE ASYNCHRONOUS PROCESS
#+begin_src emacs-lisp :tangle yes
(cl-defun sfmm--helper:make-async-process
    (&key command handle-success-lambda handle-error-lambda)
  "Make async process"
  (let ((buffer-command-history "salesforce-command-history")
        (buffer-stdout (generate-new-buffer "salesforce-process"))
        (process-identity "salesforce-process")
        (buffer-view-post-process (generate-new-buffer "salesforce outcome"))
        (process-output ""))

    (with-environment-variables (("NODE_NO_WARNINGS" "1"))

      (make-process
       :name process-identity
       :buffer buffer-stdout
       :command command
       :filter
       `(lambda (process output)
          (with-current-buffer ,buffer-stdout
             (end-of-buffer)
             (insert output)))
       :sentinel
       `(lambda (process event)
          (with-current-buffer ,buffer-stdout
            (beginning-of-buffer)

            (if (json-available-p)
                (let* ((json-instance (json-parse-buffer))
                       (json-status (gethash "status" json-instance)))

                  (cond ((and (string= event "finished\n")
                              (= json-status 0))

                         (funcall ,handle-success-lambda process json-instance ,buffer-view-post-process))

                        ((or (string= event "exited abnormally with code 1\n")
                             (= json-status 1))

                         (if ,handle-error-lambda
                             (funcall ,handle-error-lambda process json-instance ,buffer-view-post-process)

                           (let ((error-name (gethash "name" json-instance))
                                 (error-message (gethash "message" json-instance)))
                             (message error-name)
                             (message error-message)
                             (alert (format "%s \nmessage: %s "
                                            error-name
                                            error-message)
                                    :title "Salesforce Alert")
                             (kill-buffer (process-buffer process)))))

                        ((string= event "deleted\n")
                         (kill-buffer (process-buffer process))))))))))))

#+end_src

*** TODO EXECUTE SYNCHRONOUS SALESFORCE COMMAND
+ override api version with custom once
#+begin_src emacs-lisp :tangle yes
(defun sfmm--helper:execute-command (command message-success)

  (sfmm--helper:make-sync-process
   command
   `(lambda (process output buffer)
      (unless (string= message-success "")
        (alert ,message-success :title "Salesforce Alert")))))
#+end_src
*** EXECUTE ASYNCHRONOUS SALESFORCE COMMAND
#+begin_src emacs-lisp :tangle yes
(cl-defun sfmm--helper:execute-async-command
    (&key command (message-success "") (message-failures ""))

  (sfmm--helper:make-async-process
   command
   `(lambda (process output buffer)
      (let* ((json (json-parse-string output))
             (is-success (sfmm--helper:get-data-hashtable "status" json)))

        (if (= is-success 1)
            (unless (string= ,message-success "")
             (alert ,message-success :title "Salesforce Alert"))
          (alert ,message-failures :title "Salesforce Alert"))))))
#+end_src
*** CONVERT HASHTABLE TO LIST DATA
#+begin_src emacs-lisp :tangle yes
(cl-defun sfmm--helper:convert-hashtable-data-to-list
    (&key hashtable-data columns (post-process nil))
  "Convert hashtable data to list"
 (let ((data '()))

   (mapcar
      `(lambda (key)
         (when (member key columns)
           (let ((value (gethash key hashtable-data)))

             (when (eq value ':null)
               (setq value " "))
             (when (eq value ':false)
               (setq value "False"))
             (when (eq value 't)
               (setq value "True"))
             (when (eq value 'nil)
               (setq value " "))

             (add-to-list 'data value 1
                          '(lambda (element1 element2) nil))

             (when ,post-process
               (funcall ,post-process key value)))))
      columns)
   data))
#+end_src
*** CUSTOM MAP LIST FUNCTION
#+begin_src emacs-lisp :tangle yes
(defun sfmm--helper:recursive-list (list-data lambda-function)
  (let* ((new-list (cdr list-data))
         (first-item (car list-data))
         (remap-list '()))

    (when (length> new-list 0)
        (setq remap-list
              (append remap-list
                      (sfmm--helper:recursive-list new-list lambda-function))))

    (add-to-list 'remap-list (funcall lambda-function first-item))))
#+end_src
*** EXTRACT DATA IN HASHTABLE
#+begin_src emacs-lisp :tangle yes
(defun sfmm--helper:get-data-hashtable (path table)
  "Get all data follow the path in hash table"
  (let* ((path-splited (split-string path "\\."))
         (key (car path-splited))
         (key-remain (cdr path-splited)))

    (if key-remain
      (sfmm--helper:get-data-hashtable
       (string-join key-remain ".")
       (gethash key table))

     (gethash key table))))
#+end_src
** BUILD TABLE FUNCTIONS
*** BUILD CTABLE COMPONENT
#+begin_src emacs-lisp :tangle yes
(cl-defun sfdx--build:make-table-component (&key column-header data buffer)
  "Use ctable to build table data"
  (let* ((column-model (mapcar 'sfdx--build:make-header-table column-header))
         (async-model
          (ctbl:async-model-wrapper data))
         (model
          (make-ctbl:model
           :column-model column-model :data async-model)))

    (with-current-buffer (pop-to-buffer buffer)
      (ctbl:create-table-component-region
           :model model)
      (ctbl:table-mode)
      (beginning-of-buffer)
      (read-only-mode))))
#+end_src
*** BUILD CTABLE HEADER TABLE
#+begin_src emacs-lisp :tangle yes
(defun sfdx--build:make-header-table (column)
  "Build header ctable"
  (let* ((header-config column)
         (title (if (assq ':title column)
                    (cdr (assq ':title column))
                  (car column)))
         (min-width
          (cdr
           (assq ':min-width header-config)))
         (max-width
          (cdr
           (assq ':max-width header-config)))
         (align
          (cdr
           (assq ':align header-config))))

    (make-ctbl:cmodel
     :title title
     :sorter 'ctbl:sort-number-lessp
     :min-width min-width
     :max-width max-width
     :align align)))
#+end_src

#+begin_src emacs-lisp :tangle yes
(defun sfmm:site:list ()
  ""
  (interactive)
  (let* ((execute-soql-code
          (sfmm--helper:generate-command (list sfmm:data-command-alias "query" "--query" "SELECT PathPrefix, Domain.Domain, Domain.HttpsOption, Site.Status, Site.SiteType FROM DomainSite"))))

    (sfmm--helper:make-sync-process
     :command execute-soql-code
     :handle-success-lambda
     (lambda (process json-instance buffer)
       (let* ((records-list (sfmm--helper:get-data-hashtable "result.records" json-instance))
              (start-index 1)
              (column-header-map #s(hash-table test equal data ("No" ((:align . 'left) (:title . "No"))))))

         (mapc
           (lambda (element)

             (let ((row `(,start-index)))
               (maphash
                (lambda (key value)
                  (let ((column-config `((:align . ,'left) (:title . ,key))))
                    (unless (hash-table-p value)
                      (cond ((eq value ':null)
                             (setq value " "))
                            ((eq value ':false)
                             (setq value "False"))
                            ((eq value 't)
                             (setq value "True")))

                      (add-to-list 'row
                                   (replace-regexp-in-string "\\([\n]\\)" "" value) 1
                                   '(lambda (element1 element2) nil))

                      (when (length> value 50)
                        (add-to-list 'column-config `(:max-width . ,'50)))

                      (puthash (format "%s" key) column-config column-header-map))))
                element)
               (setq start-index (1+ start-index))
               row))
           records-list)
         (sfdx--build:make-table-component
          :column-header (hash-table-values column-header-map)
          :data records-list
          :buffer buffer))))))
#+end_src
** HELPERS FUNCTIONS
*** KEY BINDING FUNCTIONS
#+begin_src emacs-lisp :tangle yes
(defun sfmm:binding--key (key)
  (kbd (concat sfmm:keymap-prefix " " key)))

(defun sfmm:binding--key-org (key)
  (sfmm:binding--key
   (concat sfmm:org-keymap-prefix " " key)))

(defun sfmm:binding--key-auth (key)
  (sfmm:binding--key
   (concat sfmm:auth-keymap-prefix " " key)))

(defun sfmm:binding--key-apex (key)
  (sfmm:binding--key
   (concat sfmm:apex-keymap-prefix " " key)))

(defun sfmm:binding--key-query (key)
  (sfmm:binding--key
   (concat sfmm:query-keymap-prefix " " key)))

#+end_src
*** HOOK FUNCTIONS
#+begin_src emacs-lisp :tangle yes
(defun sfmm:hook-on-handler ()
  (setq org-default-alias (sfmm:org:show-current-org))
  (when org-default-alias
    (add-to-list 'mode-line-misc-info '(" " org-default-alias " "))
    (sf:org:connect-status)))


(defun sfmm:hook-off-handler ()
  (setq org-default-alias (sfmm:org:show-current-org))
  (when org-default-alias
    (setq mode-line-misc-info
        (delete '(" " org-default-alias " ") mode-line-misc-info))))

#+end_src

** DEFINE MINOR MODE
#+begin_src emacs-lisp :tangle yes
(define-minor-mode salesforce-minor-mode
  "Toggles global salesforce minor mode."
  nil ; Inital value, nil for disabled
  :global t
  :group 'salesforce
  :lighter " salesforce-minor-mode"

  (add-hook 'salesforce-minor-mode-on-hook #'sfmm:hook-on-handler)

  (add-hook 'salesforce-minor-mode-off-hook #'sfmm:hook-off-handler))

(provide 'salesforce-minor-mode)

#+end_src
* ORG BABEL APEX
** DEPENDENCIES
#+begin_src emacs-lisp :tangle ./ob-apex.el
;;; ob-template.el --- org-babel functions for template evaluation

;; Copyright (C) your name here

;; Author: tan.nguyen@furucrm.com
;; Keywords: literate programming, reproducible research
;; Homepage: https://orgmode.org
;; Version: 0.01

;;; License:

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to the
;; Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
;; Boston, MA 02110-1301, USA.

;;; Commentary:

;; This file is not intended to ever be loaded by org-babel, rather it is a
;; template for use in adding new language support to Org-babel. Good first
;; steps are to copy this file to a file named by the language you are adding,
;; and then use `query-replace' to replace all strings of "template" in this
;; file with the name of your new language.

;; After the `query-replace' step, it is recommended to load the file and
;; register it to org-babel either via the customize menu, or by evaluating the
;; line: (add-to-list 'org-babel-load-languages '(template . t)) where
;; `template' should have been replaced by the name of the language you are
;; implementing (note that this applies to all occurrences of 'template' in this
;; file).

;; After that continue by creating a simple code block that looks like e.g.
;;
;; #+begin_src template

;; test

;; #+end_src

;; Finally you can use `edebug' to instrumentalize
;; `org-babel-expand-body:template' and continue to evaluate the code block. You
;; try to add header keywords and change the body of the code block and
;; reevaluate the code block to observe how things get handled.

;;
;; If you have questions as to any of the portions of the file defined
;; below please look to existing language support for guidance.
;;
;; If you are planning on adding a language to org-babel we would ask
;; that if possible you fill out the FSF copyright assignment form
;; available at https://orgmode.org/request-assign-future.txt as this
;; will make it possible to include your language support in the core
;; of Org-mode, otherwise unassigned language support files can still
;; be included in the contrib/ directory of the Org-mode repository.


;;; Requirements:

;; Use this section to list the requirements of this language.  Most
;; languages will require that at least the language be installed on
;; the user's system, and the Emacs major mode relevant to the
;; language be installed as well.

(require 'ob)
(require 'ob-ref)
(require 'ob-comint)
(require 'ob-eval)
(require 'salesforce-minor-mode)
#+end_src

** Extensions
#+begin_src emacs-lisp :tangle ./ob-apex.el
(add-to-list 'org-babel-tangle-lang-exts '("cls" . "apex"))
#+end_src

** DEFAULT HEADER ARGS
#+begin_src emacs-lisp :tangle ./ob-apex.el
;; optionally declare default header arguments for this language
(defvar org-babel-default-header-args:apex '((:results . "none")
                                             (:org . "")
                                             (:log-filter-type . "none")
                                             (:log-filter-value . "none")))


(defvar org-babel-default-inline-header-args:apex '((:results . "none")
                                                    (:org . "")
                                                    (:log-filter-type . "none")
                                                    (:log-filter-value . "none")))
#+end_src

** EXPAND SOURCE CODE
#+begin_src emacs-lisp :tangle ./ob-apex.el
;; This function expands the body of a source code block by doing things like
;; prepending argument definitions to the body, it should be called by the
;; `org-babel-execute:template' function below. Variables get concatenated in
;; the `mapconcat' form, therefore to change the formatting you can edit the
;; `format' form.

(defun org-babel-expand-body:apex (body params &optional processed-params)
  "Expand BODY according to PARAMS, return the expanded body."
  (require 'inf-template nil t)
  (let ((vars
         (org-babel--get-vars
          (or processed-params
              (org-babel-process-params params)))))

    (concat
     (mapconcat #'binding-declare-variable vars "\n")
     "\n" body "\n")))
#+end_src

** EVALUATE APEX CODE
#+begin_src emacs-lisp :tangle ./ob-apex.el
;; This is the main function which is called to evaluate a code
;; block.

;; This function will evaluate the body of the source code and
;; return the results as emacs-lisp depending on the value of the
;; :results header argument
;; output means that the output to STDOUT will be captured and returned
;; value means that the value of the last statement in the source code block will be returned

;; The most common first step in this function is the expansion of the
;; PARAMS argument using `org-babel-process-params'.

;; Please feel free to not implement options which aren't appropriate
;; for your language (e.g. not all languages support interactive "session" evaluation).  Also you are free to define any new header
;; arguments which you feel may be useful -- all header arguments
;; specified by the user will be available in the PARAMS variable.

(defun org-babel-execute:apex (body params)
  (let* ((processed-params (org-babel-process-params params))
         (filter-type (assq :filter-type processed-params))
         (full-body (org-babel-expand-body:apex
                        body params processed-params)))

    (execute-apex-code processed-params full-body)))
#+end_src

** EXECUTE APEX BLOCK CODE
#+begin_src emacs-lisp :tangle ./ob-apex.el
(defun execute-apex-code (processed-params content)
  (let* ((uuid (org-id-uuid))
         (buffer (buffer-file-name))
         (tempfile (make-temp-file "temp-code"))
         (result-eval (format "%s" (cdr (assq :results processed-params))))
         (command
           (sfmm--helper:generate-command (list "apex" "run" "-f" tempfile "--json")))
         process 'nil)

   (write-region content nil tempfile)

   (cond ((not (eq (cdr (assq :org processed-params))
                   ""))
          (setq command (append command
                                (list "-o" (cdr (assq :org processed-params)))))))

   ;; Clear default result
   (org-babel-remove-result)

   (unless (string= result-eval "none")
     (re-search-forward "#\\+end_src")
     ;; Insert new result with uuid
     (insert (format "\n\n#+begin_src apex-log :uuid %s\n %s\n#+end_src\n"
                     uuid
                     uuid)))

   
   (sfmm--helper:make-async-process
    :command command
    :handle-success-lambda
    `(lambda (process json-instance buffer)

       (let ((log-content (sfmm--helper:get-data-hashtable "result.logs" json-instance))
             (log-filter-type ,(format "%s" (cdr (assq :log-filter-type processed-params))))
             (log-filter-value ,(format "%s" (cdr (assq :log-filter-value processed-params)))))

         (unless (or (equal log-filter-type "none")
                     (null log-filter-type))
           (let ((debug-keywords '("DEBUG"))
                 (executable-keywords '("VARIABLE_ASSIGNMENT"
                                        "STATEMENT_EXECUTE"
                                        "METHOD_ENTRY"
                                        "CONSTRUCTOR_EXIT"
                                        "CODE_UNIT_STARTED"))
                 (system-keywords '("VARIABLE_SCOPE_BEGIN"
                                    "USER_INFO"
                                    "EXECUTION_STARTED"
                                    "CODE_UNIT_STARTED"
                                    "HEAP_ALLOCATE"
                                    "STATEMENT_EXECUTE"
                                    "METHOD_ENTRY"))
                 (groverment-keywords '("LIMIT_USAGE_FOR_NS"
                                        "Number of"
                                        "Maximum CPU"
                                        "Maximum heap")))

              (setq log-content
                    (mapconcat (lambda (line)
                                 (cond ((and (equal log-filter-type "DEBUG")
                                             (string-match (regexp-opt debug-keywords) line))

                                        (concat line "\n"))
                                       ((and (equal log-filter-type "FILTER")
                                             (search log-filter-value line))
                                        (concat line "\n"))
                                       ((and (equal log-filter-type "EXECUTABLE")
                                             (string-match (regexp-opt executable-keywords) line))
                                        (concat line "\n"))
                                       ((and (equal log-filter-type "SYSTEM")
                                             (string-match (regexp-opt system-keywords) line))

                                        (concat line "\n"))
                                       ((and (eq log-filter-type "GOVERNMENT")
                                             (match-string (regexp-opt groverment-keywords) line))
                                        (concat line "\n"))))
                              (split-string log-content "\n")
                              ""))))

         (unless (equal ,result-eval "none")

           (with-current-buffer (find-file-noselect ,buffer)
             (beginning-of-buffer)
             (re-search-forward ,uuid)
             (delete-line)

             (insert log-content)))

         (alert "Run apex code complete"
                :title "Salesforce Alert"))))))

(defun binding-declare-variable (pair)
  (let* ((var
          (split-string
            (format "%s"(car pair)) "\\."))
         (var-type (car var))
         (var-name (car (cdr var)))
         (value
          (org-babel-template-var-to-template
           (cdr pair))))

    (format
     "%s %s = %s;"
     var-type
     var-name
     (if (string= var-type "String")
       (format "'%s'" value)
       value))))

(defun org-babel-prep-session:apex (session params)
  "Prepare SESSION according to the header arguments specified in PARAMS.")


(defun org-babel-template-var-to-template (var)
  "Convert an elisp var into a string of template source code
specifying a var of the same value."
  (format "%s" var))

(defun org-babel-template-table-or-string (results)
  "If the results look like a table, then convert them into an
Emacs-lisp table, otherwise return the results as a string.")


(defun org-babel-template-initiate-session (&optional session)
  "If there is not a current inferior-process-buffer in SESSION then create.
Return the initialized session."
  (unless (string= session "none")))

(provide 'ob-apex)
#+end_src
* LOG MODE
#+begin_src emacs-lisp :tangle apex-log-mode.el
(defface salesforce-details-log-face '((t :foreground "#2D4356"))
  "Face for detail in log file"
  :group 'salesforce-log)

(defface salesforce-groverment-log-face '((t :foreground "#6DA9E4"))
  "Face for groverment in log file"
  :group 'salesforce-log)

(defface salesforce-execute-log-face '((t :foreground "#6C9BCF"))
  "Face for execute in log file"
  :group 'salesforce-log)

(defface salesforce-run-mode-face '((t :foreground "#576CBC"))
  "Face for running mode in log file"
  :group 'salesforce-log)

(defface salesforce-log-text-face '((t :foreground "#EEEEEE"))
  "Face for running mode in log file"
  :group 'salesforce-log)

(defface salesforce-log-line-face '((t :foreground "#2DCDDF"))
  "Face for line code in log file"
  :group 'salesforce-log)

(defface salesforce-log-timestamp-face '((t :foreground "#4D4D4D"))
  "Face for timestamp in log file"
  :group 'salesforce-log)

(defface salesforce-groverment-value-face '((t :foreground "#6C9BCF"))
  "Face for groverment value in log file"
  :group 'salesforce-log)

(defface salesforce-groverment-limit-face '((t :foreground "#D21312"))
  "Face for groverment limit in log file"
  :group 'salesforce-log)

(defcustom salesforce-function-event-keywords '("SYSTEM_METHOD_EXIT"
                                                "SYSTEM_METHOD_ENTRY"
                                                "METHOD_ENTRY"
                                                "METHOD_EXIT")
  ""
  :type 'list
  :group 'salesforce-log)

(defcustom salesforce-groverment-event-keywords '("HEAP_ALLOCATE"
                                                  "LIMIT_USAGE_FOR_NS"
                                                  "Number of SOQL queries"
                                                  "Number of query rows"
                                                  "Number of SOSL queries"
                                                  "Number of DML statements"
                                                  "Number of Publish Immediate DML"
                                                  "Number of DML rows"
                                                  "Maximum CPU time"
                                                  "Maximum heap size"
                                                  "Number of callouts"
                                                  "Number of Email Invocations"
                                                  "Number of future calls"
                                                  "Number of queueable jobs added to the queue"
                                                  "Number of Mobile Apex push calls"
                                                  "CUMULATIVE_LIMIT_USAGE"
                                                  "CUMULATIVE_LIMIT_USAGE_END")
  ""
  :type 'list
  :group 'salesforce-log)

(defcustom salesforce-execute-event-keywords '("STATEMENT_EXECUTE"
                                               "CODE_UNIT_STARTED"
                                               "CODE_UNIT_FINISHED"
                                               "EXECUTION_STARTED"
                                               "EXECUTION_FINISHED")
  ""
  :type 'list
  :group 'salesforce-log)

(defcustom salesforce-mode-event-keywords '("SYSTEM_MODE_ENTER"
                                            "SYSTEM_MODE_EXIT")
  ""
  :type 'list
  :group 'salesforce-log)

(defcustom log-details-keywords-regex "\\(\\s\\S\\)"
  ""
  :group 'salesforce-log)

(setq salesforce-font-lock
      (let ((salesforce-function-event-keywords-regex (regexp-opt salesforce-function-event-keywords 'word))
            (salesforce-groverment-event-keywords-regex (regexp-opt salesforce-groverment-event-keywords 'word))
            (salesforce-execute-event-keywords-regex (regexp-opt salesforce-execute-event-keywords 'word))
            (salesforce-mode-event-keywords-regex (regexp-opt salesforce-mode-event-keywords 'word)))

        `((,salesforce-groverment-event-keywords-regex . 'salesforce-groverment-log-face)
          (,salesforce-execute-event-keywords-regex . 'salesforce-execute-log-face)
          (,salesforce-function-event-keywords-regex . 'font-lock-function-name-face)
          (,salesforce-mode-event-keywords-regex . 'salesforce-run-mode-face)
          ("\\([0-9]+\\) out of \\([0-9]+\\)" . ((1 'salesforce-groverment-value-face) (2 'salesforce-groverment-limit-face)))
          ("[0-9]\\{0,2\\}:[0-9]\\{0,2\\}:[0-9]\\{0,2\\}.[0-9]\\{0,3\\}" . 'salesforce-log-timestamp-face)
          ("\\[\\([0-9]+\\)\\]" . (1 'salesforce-log-line-face)))))



(define-derived-mode apex-log-mode fundamental-mode "apex-log"
  "Major mode for log salesforce."

  (setq font-lock-defaults '((salesforce-font-lock))))

(provide 'apex-log-mode)
#+end_src
* ORG BABEL APEX LOG
#+begin_src emacs-lisp :tangle ./ob-apex-log.el
;;; ob-template.el --- org-babel functions for template evaluation

;; Copyright (C) your name here

;; Author: tan.nguyen@furucrm.com
;; Keywords: literate programming, reproducible research
;; Homepage: https://orgmode.org
;; Version: 0.01

;;; License:

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to the
;; Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
;; Boston, MA 02110-1301, USA.

;;; Commentary:

;; This file is not intended to ever be loaded by org-babel, rather it is a
;; template for use in adding new language support to Org-babel. Good first
;; steps are to copy this file to a file named by the language you are adding,
;; and then use `query-replace' to replace all strings of "template" in this
;; file with the name of your new language.

;; After the `query-replace' step, it is recommended to load the file and
;; register it to org-babel either via the customize menu, or by evaluating the
;; line: (add-to-list 'org-babel-load-languages '(template . t)) where
;; `template' should have been replaced by the name of the language you are
;; implementing (note that this applies to all occurrences of 'template' in this
;; file).

;; After that continue by creating a simple code block that looks like e.g.
;;
;; #+begin_src template

;; test

;; #+end_src

;; Finally you can use `edebug' to instrumentalize
;; `org-babel-expand-body:template' and continue to evaluate the code block. You
;; try to add header keywords and change the body of the code block and
;; reevaluate the code block to observe how things get handled.

;;
;; If you have questions as to any of the portions of the file defined
;; below please look to existing language support for guidance.
;;
;; If you are planning on adding a language to org-babel we would ask
;; that if possible you fill out the FSF copyright assignment form
;; available at https://orgmode.org/request-assign-future.txt as this
;; will make it possible to include your language support in the core
;; of Org-mode, otherwise unassigned language support files can still
;; be included in the contrib/ directory of the Org-mode repository.


;;; Requirements:

;; Use this section to list the requirements of this language.  Most
;; languages will require that at least the language be installed on
;; the user's system, and the Emacs major mode relevant to the
;; language be installed as well.

;;; Code:
(require 'ob)
(require 'ob-ref)
(require 'ob-comint)
(require 'ob-eval)
(require 'salesforce-minor-mode)
;; possibly require modes required for your language
#+end_src

** DEPENDENCIES
#+begin_src emacs-lisp :tangle ./ob-apex-log.el
;; optionally define a file extension for this language
(add-to-list 'org-babel-tangle-lang-exts '("log" . "apex-log"))
#+end_src

** DEFINE HEADERS
#+begin_src emacs-lisp :tangle ./ob-apex-log.el
;; optionally declare default header arguments for this language
(defvar org-babel-default-header-args:apex-log '((:tangle "yes")
                                                 (:class-test . "")
                                                 (:org . "")
                                                 (:log-id . "")
                                                 (:number . "1")
                                                 (:filter-type . "")
                                                 (:filter-value . "")))

(defvar org-babel-default-inline-header-args:apex-log '((:org . "")
                                                        (:log-id . "")
                                                        (:class-test . "")
                                                        (:number . "1")
                                                        (:filter-type . "")
                                                        (:filter-value . "")))
#+end_src

** EXPAND BODY APEX LOG
#+begin_src emacs-lisp :tangle ./ob-apex-log.el
;; This function expands the body of a source code block by doing things like
;; prepending argument definitions to the body, it should be called by the
;; `org-babel-execute:template' function below. Variables get concatenated in
;; the `mapconcat' form, therefore to change the formatting you can edit the
;; `format' form.
(defun org-babel-expand-body:apex-log (body params &optional processed-params)
  "Expand BODY according to PARAMS, return the expanded body."
  (require 'inf-template nil t)
  (let ((vars (org-babel--get-vars (or processed-params (org-babel-process-params params)))))
    (concat
     (mapconcat ;; define any variables
      (lambda (pair)
        (format "%s=%S"
                (car pair) (org-babel-template-var-to-template (cdr pair))))
      vars "\n")
     "\n" body "\n")))
#+end_src

** EXECUTE APEX LOG
#+begin_src emacs-lisp :tangle ./ob-apex-log.el
;; This is the main function which is called to evaluate a code
;; block.
;;
;; This function will evaluate the body of the source code and
;; return the results as emacs-lisp depending on the value of the
;; :results header argument
;; - output means that the output to STDOUT will be captured and
;;   returned
;; - value means that the value of the last statement in the
;;   source code block will be returned
;;
;; The most common first step in this function is the expansion of the
;; PARAMS argument using `org-babel-process-params'.
;;
;; Please feel free to not implement options which aren't appropriate
;; for your language (e.g. not all languages support interactive
;; "session" evaluation).  Also you are free to define any new header
;; arguments which you feel may be useful -- all header arguments
;; specified by the user will be available in the PARAMS variable.
(defun org-babel-execute:apex-log (body params)
  "Execute a block of Template code with org-babel.
This function is called by `org-babel-execute-src-block'"
  (message "executing Template source code block")
  (let* ((processed-params (org-babel-process-params params))
         ;; set the session if the value of the session keyword is not the
         ;; string `none'
         ;; (session (unless (string= value "none")
         ;;           (org-babel-template-initiate-session
         ;;            (cdr (assq :session processed-params)))))
         ;; variables assigned for use in the block
         (vars (org-babel--get-vars processed-params))
         (result-params (assq :result-params processed-params))
         ;; either OUTPUT or VALUE which should behave as described above
         (result-type (assq :result-type processed-params))
         ;; expand the body with `org-babel-expand-body:template'
         (full-body (org-babel-expand-body:apex-log
                     body params processed-params)))

     (if (null (assq :test-class processed-params))
         (ob-apex-log:filter-log processed-params))
     (ob-apex-log:get-log-test-class processed-params)))
    ;; actually execute the source-code block either in a session or
    ;; possibly by dropping it to a temporary file and evaluating the
    ;; file.
    ;;
    ;; for session based evaluation the functions defined in
    ;; `org-babel-comint' will probably be helpful.
    ;;
    ;; for external evaluation the functions defined in
    ;; `org-babel-eval' will probably be helpful.
    ;;
    ;; when forming a shell command, or a fragment of code in some
    ;; other language, please preprocess any file names involved with
    ;; the function `org-babel-process-file-name'. (See the way that
    ;; function is used in the language files)

#+end_src
** RUN TEST CLASS
#+begin_src emacs-lisp :tangle yes
(defun ob-apex-log:get-log-test-class (process-params)
  "Get log from test class executed"
  (let* ((test-class-name (cdr (assq :test-class process-params)))
         (sfmm--helper:generate-command (list sfmm:apex-command-alias "run" "test" "--tests" test-class-name "--test-level" "RunSpecifiedTests" "--json")))

    (org-babel-remove-result)
 
    (re-search-backward "#\\+end_src")
    (previous-line)
    (newline)
    (insert uuid)

    (sfmm--helper:make-async-process
     :command command
     :handle-success-lambda
     (lambda (process json-instance buffer)
       (sfmm:apex:get-log
        :number 1
        :post-log-handle
        `(lambda (log-content)

           (let ((filter-type ,(upcase (format "%s" (cdr (assq :filter-type processed-params)))))
                 (filter-value ,(cdr (format "%s" (assq :filter-value processed-params)))))

             (unless (or (equal filter-type "none"
                          (null filter-type)))
                (let ((debug-keywords '("DEBUG"))
                      (executable-keywords '("VARIABLE_ASSIGNMENT"
                                             "STATEMENT_EXECUTE"
                                             "METHOD_ENTRY"
                                             "CONSTRUCTOR_EXIT"
                                             "CODE_UNIT_STARTED"))
                      (system-keywords '("VARIABLE_SCOPE_BEGIN"
                                         "USER_INFO"
                                         "EXECUTION_STARTED"
                                         "CODE_UNIT_STARTED"
                                         "HEAP_ALLOCATE"
                                         "STATEMENT_EXECUTE"
                                         "METHOD_ENTRY"))
                      (groverment-keywords '("LIMIT_USAGE_FOR_NS"
                                             "Number of"
                                             "Maximum CPU"
                                             "Maximum heap")))

                   (setq log-content
                         (mapconcat (lambda (line)
                                      (cond ((and (equal filter-type "DEBUG")
                                                  (string-match (regexp-opt debug-keywords) line))

                                             (concat line "\n"))
                                            ((and (equal filter-type "FILTER")
                                                  (search filter-value line))
                                             (concat line "\n"))
                                            ((and (equal filter-type "EXECUTABLE")
                                                  (string-match (regexp-opt executable-keywords) line))
                                             (concat line "\n"))
                                            ((and (equal filter-type "SYSTEM")
                                                  (string-match (regexp-opt system-keywords) line))

                                             (concat line "\n"))
                                            ((and (eq filter-type "GOVERNMENT")
                                                  (match-string (regexp-opt groverment-keywords) line))
                                             (concat line "\n"))))
                                   (split-string log-content "\n")
                                   ""))))))

        (with-current-buffer ,buffer
          (beginning-of-buffer)
          (re-search-forward ,uuid)
          (forward-line -1)
          (newline)
          (insert (concat "|-------------------LOG--------------------------|"
                   "\n" log-content))
          (next-line)
          (delete-line)

          (alert "get log success"
                 :title "Salesforce Alert")))))))
#+end_src

** FILTER LOG CONTENT
#+begin_src emacs-lisp :tangle ./ob-apex-log.el
(defun ob-apex-log:filter-log (processed-params)
  "Filter match string in log"
  (let* ((uuid (org-id-uuid))
         (log-id (format "%s" (cdr (assq :log-id processed-params))))
         (org (format "%s" (cdr (assq :org processed-params))))
         (number (format "%s" (cdr (assq :number processed-params))))
         (buffer (current-buffer)))

         ;; (filterd-content (mapconcat
         ;;                   (lambda (line)
         ;;                     (when (string-match-p keyword line)
         ;;                       line))
         ;;                   (split-string log-content "\n")
         ;;                   "\n")))
   (org-babel-remove-result)

   (re-search-backward "#\\+end_src")
   (previous-line)
   (newline)
   (insert uuid)

   (sfmm:apex:get-log
     :log-id log-id
     :number number
     :org org
     :post-log-handle
     `(lambda (log-content)
        (let ((filter-type ,(upcase (format "%s" (cdr (assq :filter-type processed-params)))))
              (filter-value ,(cdr (format "%s" (assq :filter-value processed-params)))))

          (unless (or (equal filter-type "none"
                       (null filter-type)))
             (let ((debug-keywords '("DEBUG"))
                   (executable-keywords '("VARIABLE_ASSIGNMENT"
                                          "STATEMENT_EXECUTE"
                                          "METHOD_ENTRY"
                                          "CONSTRUCTOR_EXIT"
                                          "CODE_UNIT_STARTED"))
                   (system-keywords '("VARIABLE_SCOPE_BEGIN"
                                      "USER_INFO"
                                      "EXECUTION_STARTED"
                                      "CODE_UNIT_STARTED"
                                      "HEAP_ALLOCATE"
                                      "STATEMENT_EXECUTE"
                                      "METHOD_ENTRY"))
                   (groverment-keywords '("LIMIT_USAGE_FOR_NS"
                                          "Number of"
                                          "Maximum CPU"
                                          "Maximum heap")))

                (setq log-content
                      (mapconcat (lambda (line)
                                   (cond ((and (equal filter-type "DEBUG")
                                               (string-match (regexp-opt debug-keywords) line))

                                          (concat line "\n"))
                                         ((and (equal filter-type "FILTER")
                                               (search filter-value line))
                                          (concat line "\n"))
                                         ((and (equal filter-type "EXECUTABLE")
                                               (string-match (regexp-opt executable-keywords) line))
                                          (concat line "\n"))
                                         ((and (equal filter-type "SYSTEM")
                                               (string-match (regexp-opt system-keywords) line))

                                          (concat line "\n"))
                                         ((and (eq filter-type "GOVERNMENT")
                                               (match-string (regexp-opt groverment-keywords) line))
                                          (concat line "\n"))))
                                (split-string log-content "\n")
                                "")))))

        (with-current-buffer ,buffer
          (beginning-of-buffer)
          (re-search-forward ,uuid)
          (forward-line -1)
          (newline)
          (insert (concat "|-------------------LOG--------------------------|"
                   "\n" log-content))
          (next-line)
          (delete-line)

          (alert "get log success"
                 :title "Salesforce Alert"))))))



;; This function should be used to assign any variables in params in
;; the context of the session environment.
(defun org-babel-prep-session:apex-log (session params)
  "Prepare SESSION according to the header arguments specified in PARAMS.")


(defun org-babel-template-var-to-template (var)
  "Convert an elisp var into a string of template source code
specifying a var of the same value."
  (format "%S" var))

(defun org-babel-template-table-or-string (results)
  "If the results look like a table, then convert them into an
Emacs-lisp table, otherwise return the results as a string.")


(defun org-babel-template-initiate-session (&optional session)
  "If there is not a current inferior-process-buffer in SESSION then create.
Return the initialized session."
  (unless (string= session "none")))


(provide 'ob-apex-log)
;;; ob-template.el ends here
#+end_src
